version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sma
      MYSQL_USER: akmt_spring
      MYSQL_PASSWORD: tomoosql
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

