spring:
  profiles:
    active: local
---
spring:
  profiles: develop
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/sma
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    web:
      base-path: /
---
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.sma.domain.models.**
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sma
    username: akmt_spring
    password: tomoosql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    web:
      base-path: /
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8

