version: "3.8"
volumes:
  mysql-db:
    driver: local
services:
  db:
    build: ./mysql
    image: demo-db:0.0.1
    restart: always
    platform: linux/x86_64
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ../log/mysql:/var/log/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
  server:
    build: ./java
    image: demo-app:0.0.1
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ./gradlew clean bootRun
  front:
    build: ./frontend
    image: node:16-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: sh -c "yarn install && yarn start"
