version: "3.8"
volumes:
  mysql-db:
    driver: local
services:
  db:
    build: ./mysql
    image: demo-db:0.0.1
    restart: always
    platform: linux/x86_64
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ../log/mysql:/var/log/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sma
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    # networks:
    #   app_net:
    #     ipv4_address: 172.30.0.2
  server:
    build: ./java
    image: demo-app:0.0.1
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    command: ./gradlew clean bootRun
    env_file:
      - .env
    # networks:
    #   app_net:
    #     ipv4_address: 172.30.0.3
  front:
    build: ./frontend
    image: node:16-alpine
    volumes:
      - ./frontend:/app:cached
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: sh -c "yarn install && yarn start"
#     networks:
#       app_net:
#         ipv4_address: 172.30.0.4
# networks:
#   app_net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.30.0.0/24
