export const dummyEmployeeList = [
  {
    employeeId: 1,
    lastName: "岸田",
    firstName: "文雄",
    romanLastName: "kishida",
    romanFirstName: "fumio",
    birthday: "1957/7/29",
    age: 64,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 2,
    lastName: "菅",
    firstName: "義偉",
    romanLastName: "suga",
    romanFirstName: "yoshihide",
    birthday: "1948/12/6",
    age: 73,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 3,
    lastName: "安倍",
    firstName: "晋三",
    romanLastName: "abe",
    romanFirstName: "shinzo",
    birthday: "1954/9/21",
    age: 67,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 4,
    lastName: "野田",
    firstName: "佳彦",
    romanLastName: "noda",
    romanFirstName: "yoshihiko",
    birthday: "1957/5/20",
    age: 65,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 5,
    lastName: "菅",
    firstName: "直人",
    romanLastName: "kan",
    romanFirstName: "naoto",
    birthday: "1946/10/10",
    age: 75,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 6,
    lastName: "鳩山",
    firstName: "由紀夫",
    romanLastName: "hatoyama",
    romanFirstName: "yukio",
    birthday: "1947/2/11",
    age: 75,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 7,
    lastName: "麻生",
    firstName: "太郎",
    romanLastName: "aso",
    romanFirstName: "taro",
    birthday: "1940/9/20",
    age: 81,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 8,
    lastName: "福田",
    firstName: "康夫",
    romanLastName: "fukuda",
    romanFirstName: "yasuo",
    birthday: "1936/7/16",
    age: 85,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 9,
    lastName: "小泉",
    firstName: "純一郎",
    romanLastName: "koizumi",
    romanFirstName: "junichiro",
    birthday: "1942/1/8",
    age: 80,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 10,
    lastName: "森",
    firstName: "喜朗",
    romanLastName: "mori",
    romanFirstName: "yoshiro",
    birthday: "1937/7/14",
    age: 84,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "hoge@huga.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
];
