export const dummyEmployeeList = [
  {
    employeeId: 1,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 2,
    lastName: "赤松",
    firstName: "仁衣奈",
    romanLastName: "akamatsu",
    romanFirstName: "nina",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 3,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 4,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 5,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 6,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 7,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 8,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 9,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
  {
    employeeId: 10,
    lastName: "赤松",
    firstName: "知音",
    romanLastName: "akamatsu",
    romanFirstName: "tomoo",
    birthday: "1995/08/11",
    age: 26,
    gender: "man",
    phoneNumber: "090-0000-0000",
    email: "akmt@ahooo.com",
    employmentDate: "2020-04-01",
    workingForm: "正社員",
  },
];
